# Generated by Codex on 2026-06-05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_instance_app', '0013_sandbox_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxlock',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
