name: Build and push Docker image to ACR

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  acr:
    uses: CyberGoatz/github-workflows/.github/workflows/acr-build-push.yml@main
    with:
      acr_login_server: ${{ vars.ACR_LOGIN_SERVER }}
      image_name: sandbox-service
      build_type: python
    secrets: inherit
